// src/app/modules/shared/components/footer/footer.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {

  constructor() {
  }

  ngOnInit(): void {
  }

  get year(): number {
    return new Date().getFullYear();
  }

}

<div class="footer-basic wrapper">
  <footer class="container">
<!--    <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i-->
<!--      class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i-->
<!--      class="icon ion-social-facebook"></i></a></div>-->
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Home</a></li>
      <li class="list-inline-item"><a href="#">Services</a></li>
      <li class="list-inline-item"><a href="#">About</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
    </ul>
    <p class="copyright">Lbry Realm © {{year}}</p>
  </footer>
</div>

// src/components/shared/Footer.vue
<template>
  <div class="footer-basic wrapper">
    <footer class="container">
      <ul class="list-inline">
        <!--        TODO: add proper links here-->
        <li class="list-inline-item"><a href="#">Home</a></li>
        <li class="list-inline-item"><a href="#">Services</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>
      <p class="copyright">Lbry Realm © {{ year }}</p>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'Footer',
  data: () => ({
    year: new Date().getFullYear()
  })
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.wrapper {
  background-color: var(--color-hover);
  display: block;
  width: 100%;

  padding-top: 30px;
  padding-bottom: 30px;
}

.footer-basic {
  color: var(--color-initial);
}

.footer-basic ul {
  padding: 0;
  list-style: none;
  text-align: center;
  font-size: 18px;
  line-height: 1.6;
  margin-bottom: 0;
}

.footer-basic li {
  padding: 0 10px;
}

.footer-basic ul a {
  color: inherit;
  text-decoration: none;
  opacity: 0.8;
}

.footer-basic ul a:hover {
  opacity: 1;
}

.footer-basic .social {
  text-align: center;
  padding-bottom: 25px;
}

.footer-basic .social > a {
  font-size: 24px;
  width: 40px;
  height: 40px;
  line-height: 40px;
  display: inline-block;
  text-align: center;
  border-radius: 50%;
  border: 1px solid #ccc;
  margin: 0 8px;
  color: inherit;
  opacity: 0.75;
}

.footer-basic .social > a:hover {
  opacity: 0.9;
}

.footer-basic .copyright {
  margin-top: 15px;
  text-align: center;
  font-size: 13px;
  color: #aaa;
  margin-bottom: 0;
}

.list-inline {
  display: block;

  li {
    display: inline;
  }
}

/* Credit to https://epicbootstrap.com/snippets/footer-basic */

</style>
